#!/bin/bash

mkcd() {
  if [ -z "$1" ]; then
    echo "Enter a directory name"
  elif [ -d "$1" ]; then
    echo "\`$1' already exists"
  else
    mkdir -p "$1" && cd "$1" || exit 1
  fi
}

gitclone () {
    url=$1;
    reponame=$(echo "$url" | awk -F/ '{print $NF}' | sed -e 's/.git$//');
    git clone "$url" "$reponame";
    cd "$reponame" || exit;
}

gitcleanbr () {
  ! git branch -d "$(git branch --merged | grep -v '^*\\|main\\|master\\|staging\\|dev\\|develop')"
}

listr() {
	local current="$1" ; for key in $(vault list "$current" | tail +3 | grep '[^/]$') ; do echo "$current${key}" ; vault read "$current${key}" ; done ; for subdir in $(vault list "$current" | tail +3 | grep '/$') ; do echo "$current${subdir}" ; listr "$current${subdir}" ; done
}

command_exists() {
  command -v "$@" >/dev/null 2>&1
}
