
services:
  ubuntu-test:
    build: .
    container_name: ubuntu-test
    volumes:
      - ./..:/home/testuser/dotfiles
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color

  # automated-test:
  #   build: .
  #   container_name: automated-test
  #   volumes:
  #     - ./..:/home/testuser/dotfiles
  #   command: ["bash", "/home/testuser/dotfiles/test-setup.sh"]
